project_id = "mnhofrfaqnihaosvaaqa"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-permit-email]
    verify_jwt = false
  [functions.send-sms]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
