import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const TermsOfService = () => (
  <div className="min-h-screen bg-background max-w-lg mx-auto px-5 py-8 pb-20">
    <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-6">
      <ArrowLeft size={16} />
      Back
    </Link>
    <h1 className="text-2xl font-heading font-bold text-foreground mb-2">Terms of Service</h1>
    <div className="space-y-5 text-sm text-muted-foreground leading-relaxed font-body">
      <p className="text-xs text-muted-foreground/60">Effective Date: March 6, 2026 · Last Updated: March 6, 2026</p>

      <p>Welcome to WildAtlas. By creating an account or using our service you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use WildAtlas.</p>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">1. Nature of Service</h2>
        <p>WildAtlas is a <strong className="text-foreground">planning and informational tool</strong> designed to help outdoor enthusiasts monitor national park permit availability across multiple parks. We aggregate publicly available data from Recreation.gov and other public sources to provide a convenient tracking and alert experience.</p>
        <p>WildAtlas also provides AI-powered trip planning recommendations through Mochi, our in-app assistant. Mochi responses are generated by artificial intelligence and should be treated as suggestions, not professional advice.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">2. Eligibility</h2>
        <p>You must be at least 13 years of age to use WildAtlas. If you are under 18 you must have permission from a parent or legal guardian. By using WildAtlas you represent and warrant that you meet these eligibility requirements.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">3. Account Registration</h2>
        <p>To access certain features you must create an account. You agree to:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Provide accurate, current, and complete information during registration.</li>
          <li>Maintain and promptly update your account information.</li>
          <li>Keep your password secure and confidential.</li>
          <li>Accept responsibility for all activity that occurs under your account.</li>
          <li>Notify us immediately at <a href="mailto:support@wildatlas.app" className="text-primary underline">support@wildatlas.app</a> if you suspect unauthorized access to your account.</li>
        </ul>
        <p>WildAtlas reserves the right to suspend or terminate accounts that violate these terms or engage in fraudulent or abusive behavior.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">4. No Guarantee of Permit Availability</h2>
        <p className="font-medium text-foreground">WildAtlas does not guarantee permit availability.</p>
        <p>All permit inventory, cancellation data, and availability windows are sourced from Recreation.gov and other public channels. We have no control over:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Whether a permit will become available at any given time.</li>
          <li>The accuracy or timeliness of data provided by Recreation.gov or other sources.</li>
          <li>Your ability to successfully secure a permit once notified.</li>
          <li>Changes to Recreation.gov policies, APIs, or availability systems.</li>
        </ul>
        <p>Permit alerts are sent on a best-effort basis. Network delays, API rate limits, and third-party outages may affect alert delivery speed and accuracy. WildAtlas is not responsible for permits that are claimed by other users before you can act on an alert.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">5. Recreation.gov Disclaimer</h2>
        <p>WildAtlas is an independent service and is <strong className="text-foreground">not affiliated with, endorsed by, or officially connected to Recreation.gov, the National Park Service, or any United States government agency</strong>. All permit bookings are completed directly on Recreation.gov. WildAtlas does not process permit reservations or handle any government transactions.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">6. Free and Pro Plans</h2>
        <p>WildAtlas offers both free and paid subscription tiers:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong className="text-foreground">Free Plan:</strong> Limited to one active permit watch with email-only notifications.</li>
          <li><strong className="text-foreground">Pro Plan:</strong> Unlimited permit watches, SMS alerts, AI-powered insights, and priority support.</li>
        </ul>
        <p>Features available on each plan may change over time. We will notify active subscribers of any material changes to their plan benefits.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">7. Payments, Billing &amp; Refunds</h2>
        <p>Pro subscriptions are billed on a recurring monthly basis through Stripe. By subscribing you authorize WildAtlas to charge your payment method on file for each billing cycle until you cancel.</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong className="text-foreground">Cancellation:</strong> You may cancel your Pro subscription at any time through the app Settings page or Stripe customer portal. Cancellation takes effect at the end of your current billing period. You will retain Pro access until then.</li>
          <li><strong className="text-foreground">Refunds:</strong> WildAtlas offers a 7-day full refund window from the date of your initial Pro subscription purchase. To request a refund contact <a href="mailto:support@wildatlas.app" className="text-primary underline">support@wildatlas.app</a> within 7 days of purchase. Refunds are not available after the 7-day window or for subsequent billing cycles.</li>
          <li><strong className="text-foreground">Price Changes:</strong> We reserve the right to change subscription pricing. Existing subscribers will be notified at least 30 days before any price increase takes effect.</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">8. SMS Alerts &amp; Consent</h2>
        <p>By enabling SMS alerts and providing your phone number you consent to receive automated text messages from WildAtlas regarding permit availability. Standard message and data rates may apply.</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>SMS alerts are available exclusively to Pro subscribers.</li>
          <li>Message frequency varies based on permit availability and the number of active watches.</li>
          <li>You may opt out at any time by replying STOP, toggling off SMS in Settings, or deleting your account.</li>
          <li>Reply HELP for assistance or contact <a href="mailto:support@wildatlas.app" className="text-primary underline">support@wildatlas.app</a>.</li>
        </ul>
        <p>See our <Link to="/privacy" className="text-primary underline">Privacy Policy</Link> for full TCPA compliance details.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">9. User Responsibilities</h2>
        <p>By using WildAtlas you agree to:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Use the service for personal, non-commercial purposes only.</li>
          <li>Provide accurate account and contact information.</li>
          <li>Not attempt to circumvent any access controls, rate limits, or security measures.</li>
          <li>Not use automated tools, bots, or scripts to interact with WildAtlas beyond normal app usage.</li>
          <li>Not reverse-engineer, decompile, or attempt to extract the source code of any proprietary components.</li>
          <li>Not resell, redistribute, or commercially exploit WildAtlas data or alerts.</li>
          <li>Submit accurate crowd reports if you choose to use the community reporting feature.</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">10. Intellectual Property</h2>
        <p>All content, design, code, branding, and features of WildAtlas are the intellectual property of WildAtlas and are protected by applicable copyright and trademark laws. You may not copy, modify, distribute, or create derivative works from any part of the service without prior written permission.</p>
        <p>The Mochi character, WildAtlas logo, and all associated visual assets are trademarks of WildAtlas.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">11. AI-Powered Features</h2>
        <p>WildAtlas uses artificial intelligence to power Mochi, our in-app assistant, and to generate permit pattern insights. AI-generated content is provided for informational purposes only and may contain inaccuracies.</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>AI responses should not be relied upon as the sole basis for trip planning decisions.</li>
          <li>WildAtlas is not responsible for actions taken based on AI-generated recommendations.</li>
          <li>Conversation data may be processed by third-party AI providers to generate responses. See our <Link to="/privacy" className="text-primary underline">Privacy Policy</Link> for details.</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">12. Limitation of Liability</h2>
        <p className="font-medium text-foreground">WildAtlas is provided "as is" and "as available" without warranties of any kind, either express or implied.</p>
        <p>To the maximum extent permitted by applicable law, WildAtlas and its operators shall not be liable for:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Missed permits or failed alert delivery.</li>
          <li>Inaccurate, incomplete, or delayed permit data.</li>
          <li>Service downtime, interruptions, or technical failures.</li>
          <li>Any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of the service.</li>
          <li>Loss of data, revenue, or anticipated savings.</li>
          <li>Actions taken based on AI-generated recommendations.</li>
        </ul>
        <p>In no event shall WildAtlas's total liability exceed the amount you paid for the service in the 12 months preceding the claim.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">13. Indemnification</h2>
        <p>You agree to indemnify, defend, and hold harmless WildAtlas, its operators, and affiliates from and against any claims, damages, losses, liabilities, and expenses (including reasonable attorney fees) arising from your use of the service, your violation of these terms, or your violation of any rights of a third party.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">14. Termination</h2>
        <p>We reserve the right to suspend or terminate your access to WildAtlas at any time, with or without cause, and with or without notice. Upon termination:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Your right to use the service ceases immediately.</li>
          <li>Active Pro subscriptions will not be renewed but access continues through the end of the current billing period.</li>
          <li>You may request deletion of your personal data in accordance with our <Link to="/privacy" className="text-primary underline">Privacy Policy</Link>.</li>
        </ul>
        <p>You may delete your account at any time through the app Settings page.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">15. Governing Law &amp; Disputes</h2>
        <p>These terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from or relating to these terms or your use of WildAtlas shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association, except where prohibited by law.</p>
        <p>You agree to waive any right to participate in a class action lawsuit or class-wide arbitration against WildAtlas.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">16. Severability</h2>
        <p>If any provision of these terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that the remaining provisions remain in full force and effect.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">17. Changes to Terms</h2>
        <p>We may update these Terms of Service from time to time. When we do we will update the "Last Updated" date at the top of this page and notify active users by email. Your continued use of WildAtlas after changes are posted constitutes acceptance of the updated terms.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-heading font-semibold text-foreground">18. Contact</h2>
        <p>For questions about these Terms of Service:</p>
        <ul className="list-none pl-0 space-y-1">
          <li>Email: <a href="mailto:support@wildatlas.app" className="text-primary underline">support@wildatlas.app</a></li>
          <li>Website: <a href="https://wildatlasnp.lovable.app" className="text-primary underline">WildAtlas.com</a></li>
        </ul>
        <p className="pt-1">WildAtlas<br />Operated as a sole proprietorship<br />United States</p>
      </section>

      <p className="text-xs text-muted-foreground/50 pt-4 border-t border-border">© 2026 WildAtlas. All Rights Reserved.</p>
    </div>
  </div>
);

export default TermsOfService;
